### ISSUE TITLE
Larger Time Spans

### ISSUE THREAD

**Issue by langfingaz** [aeri/Florae#3]
Many thanks for developing this app!

I have an aloe vera that I do not fertilize but would like to repot in fresh soil every 2-3 years. Currently you can select a maximum of 60 days as transplant period.

Can you imagine increasing the input method to something greater than 60, e.g. 720 (or 999)? I think this should have no impact on how good one can select small numbers, but make the app more flexible :)

**Comment by aeri** [comment]
Hello, thanks for your suggestion, I find the change you propose very interesting as that would allow to set long term plant care.

I set a maximum of 60 days to not show a too long number picker, so I have discarded it and created a new cycle selector with text input, to give a much more pleasant experience to the user, I think even for short maintenances.

This will be the result: 

![xs](https://github.com/aeri/Florae/assets/23065231/1d25736c-91fb-4471-b456-db4ccba27b97)

I will publish soon a version with this change.
